### PR TITLE
Raise on non-existing fields in Protobuf.Builder.new/2

### PR DESCRIPTION
**Pull request by whatyouhide**
cc @keathley as mentioned in #76 and cc @tony612 for review 🙃

### CODE REVIEW

**Comment by whatyouhide** [comment]
Ping @tony612 :)

**Comment by tony612** [comment]
@whatyouhide Thanks for the PR. I'm thinking if it's better to have a `new!` function and keep the original one. The reason is sometimes I found it's useful to use a superset map to create a pb struct. How do you like it? @keathley

**Comment by whatyouhide** [comment]
@tony612 we use this library pretty extensively at work and in my experience this is definitely an extremely unexpected behaviour, so much so that I've always considered this a bug. I think it's much more common to misspell a field name and only catch it when encoding than to desire this behaviour. Ultimately, up to you, I can create new! :)

**Comment by tony612** [comment]
@whatyouhide I guess that's why we have both `struct` and `struct!`? Sometimes we specify the keys explicitly
```
Foo.new(a: 1, b: "foo")
```
But sometimes we use a map to build it like
```
map = got_from_somewhere_else()
Foo.new(map)
```
It's hard to guarantee the `map` in the later example match very well with our struct, especially in a dynamic language like Elixir.

**Comment by whatyouhide** [comment]
@tony612 okay, we'll switch completely to `new!` and forget about `new` then 😄 I updated the PR, can you take a look?

**Comment by tony612** [comment]
@whatyouhide Looks like `new!` should be used in the test?

**Comment by whatyouhide** [comment]
Yep, I actually forgot to push this code but we need to generate the `new!/1` function in protobuf modules too 😄 I just pushed the new code and the updated test!

**Comment by keathley** [comment]
Sorry I didn't respond earlier. I'm glad y'all ended up using `new!` since it allows `new` to remain "open" which should allow more re-use of existing maps. :+1:

**Pull request merged**
